"""Deterministic FAKE provider. It is NOT a language model: it classifies by keyword overlap, builds extractive
answers/questions from the supplied passages, and grades short answers by keyword coverage. Its output only proves that
the workflow, validation and persistence work; it says nothing about the quality a real model would deliver."""
from __future__ import annotations

import hashlib
import logging
import re

from app.agents.practice import prompt_hash
from app.knowledge.chunker import split_sentences
from app.knowledge.service import STOPWORDS
from app.llm.schemas import (
    ChunkView, Citation, DoubtAnalysis, EvaluateRequest, EvaluationOut, ExplainRequest, Explanation,
    PracticeItemDraft, PracticeRequest, PracticeSet, UnderstandRequest,
)

log = logging.getLogger("eduos.llm.fake")

NOTE = "Generated by the deterministic FAKE provider (extractive, no language model)."
VERSIONS = {"understand": "fake-understand@1", "explain": "fake-explain@1", "practice": "fake-practice@1",
            "evaluate": "fake-evaluate@1"}


def _stem(t: str) -> str:
    for suf in ("ing", "ed", "es", "s", "e"):
        if len(t) > len(suf) + 3 and t.endswith(suf):
            return t[: -len(suf)]
    return t


def _tokens(text: str) -> list[str]:
    return [_stem(t) for t in re.findall(r"[a-z0-9]+", text.lower()) if t not in STOPWORDS and len(t) > 1]


def _h(*parts: str) -> int:
    return int(hashlib.sha256("|".join(parts).encode()).hexdigest()[:8], 16)


class FakeLLMProvider:
    name = "fake"
    model = "fake-extractive-1"

    def prompt_version(self, op: str) -> str:
        return VERSIONS[op]

    def status(self) -> dict:
        return {"provider": self.name, "model": self.model, "reachable": True}

    # ------------------------------------------------------------------ understand
    def understand(self, req: UnderstandRequest) -> DoubtAnalysis:
        text = " ".join([*req.history, req.doubt_text]).lower()
        words = re.findall(r"[a-z0-9]+", text)
        scores: list[tuple[int, str]] = []
        for t in req.topics:
            kws = {k.strip().lower() for k in t.keywords if k.strip()} | {t.name.lower()}
            score = sum(1 for k in kws if k and re.search(r"(?<![a-z0-9])" + re.escape(k) + r"(?![a-z0-9])", text))
            scores.append((score, t.id))
        scores.sort(key=lambda x: (-x[0], x[1]))
        best_score, best_id = scores[0] if scores else (0, None)
        intent = "procedural" if re.search(r"\b(how do|how to|calculate|compute)\b", text) else (
            "error_diagnosis" if re.search(r"\b(wrong|mistake|error|confus)", text) else "conceptual")
        difficulty = "easy" if len(words) < 8 else ("hard" if re.search(r"\b(why|compare|difference|derive|trade-?off)\b", text) else "medium")
        if len(words) < 3:
            return DoubtAnalysis(topic_id=None, intent="other", clarity="ambiguous", classification_confidence=0.1,
                                 clarification_question="Could you describe your question in a full sentence?")
        if best_score == 0:
            return DoubtAnalysis(topic_id=None, intent=intent, clarity="ambiguous", classification_confidence=0.2,
                                 clarification_question=("Which Computer Networks topic is this about "
                                                         "(for example TCP, IP addressing, or routing)?"))
        sec = [i for s, i in scores[1:] if s > 0][:2]
        hyps = []
        if intent == "error_diagnosis" or "confus" in text or "mix" in text:   # a suspected gap is only ever a hypothesis
            hyps = [{"topic_id": best_id, "description": "May confuse closely related concepts in this topic"}]
        return DoubtAnalysis(topic_id=best_id, secondary_topic_ids=sec, intent=intent, clarity="clear",
                             difficulty_estimate=difficulty, gap_hypotheses=hyps,
                             classification_confidence=min(0.95, 0.5 + 0.15 * best_score))

    # ------------------------------------------------------------------ explain
    def explain(self, req: ExplainRequest) -> Explanation:
        q = set(_tokens(req.doubt_text))
        scored: list[tuple[int, int, int, str, str]] = []  # (-overlap, chunk order, sentence order, chunk_id, sentence)
        seen: set[str] = set()  # chunk overlap repeats sentences; cite each sentence once
        for ci, ch in enumerate(req.chunks):
            for si, sent in enumerate(split_sentences(ch.text)):
                if sent in seen:
                    continue
                seen.add(sent)
                overlap = len(q & set(_tokens(sent)))
                if overlap >= 2 or (overlap >= 1 and len(q) <= 2):
                    scored.append((-overlap, ci, si, ch.chunk_id, sent))
        if not scored:
            return Explanation(
                text=("I could not find passages in your course material that address this question, so I am not "
                      "going to guess."), insufficient_context=True, provider_note=NOTE)
        scored.sort()
        picked = sorted(scored[:3], key=lambda x: (x[1], x[2]))  # restore reading order
        parts, cites = [], []
        for n, (_, _, _, chunk_id, sent) in enumerate(picked, start=1):
            parts.append(f"{sent} [{n}]")
            cites.append(Citation(chunk_id=chunk_id, quote=sent))
        text = "Here is what your course material says about this: " + " ".join(parts)
        return Explanation(text=text, citations=cites, provider_note=NOTE,
                           follow_up_check="Would you like a short practice question on this?")

    # ------------------------------------------------------------------ practice
    def generate_practice(self, req: PracticeRequest) -> PracticeSet:
        pool: list[tuple[str, str]] = []                    # (chunk_id, sentence) with enough substance, unique
        seen: set[str] = set()
        for ch in req.chunks:
            for s in split_sentences(ch.text):
                if len(s.split()) >= 7 and s not in seen:
                    seen.add(s)
                    pool.append((ch.chunk_id, s))
        topic_terms = set(_tokens(req.topic_name + " " + req.doubt_text))
        pool.sort(key=lambda cs: (-len(topic_terms & set(_tokens(cs[1]))), cs[0], cs[1]))
        items: list[PracticeItemDraft] = []
        avoid = set(req.avoid_prompt_hashes)
        wants_numeric = "numeric" in req.kinds and bool(re.search(r"subnet|prefix|cidr|mask|address", (req.topic_name + req.doubt_text).lower()))
        order = (["numeric"] if wants_numeric else []) + ["mcq", "short_text", "mcq", "short_text", "mcq", "short_text"]
        order = [k for k in order if k in req.kinds] or ["mcq"]
        chunk_page = {c.chunk_id: c.page for c in req.chunks}

        def question(kind: str, cid: str, sent: str) -> str:
            tag = f"page {chunk_page.get(cid, 0)}, passage {cid[:4]}, sentence {_h(sent) % 1000}"
            if kind == "mcq":
                return f"Which statement about {req.topic_name} appears in your course material ({tag})?"
            clause = " ".join(sent.split()[:9]).rstrip(",.;")
            return f"In your own words, explain the idea behind: \"{clause}...\" ({tag})"

        # pass 1: choose the key sentence of every planned item (skipping questions this student has already seen)
        plan: list[tuple[str, str, str, str]] = []                      # (kind, prompt, chunk_id, key sentence)
        used = 0
        for kind in order:
            if len(plan) >= req.count:
                break
            if kind == "numeric":
                n = 24 + _h(req.topic_id, req.doubt_text) % 7                         # /24 .. /30
                prompt = f"How many usable host addresses does a /{n} IPv4 subnet contain?"
                if prompt_hash(prompt) not in avoid and not any(k == "numeric" for k, *_ in plan):
                    plan.append(("numeric", prompt, "", str(2 ** (32 - n) - 2)))
                continue
            while used < len(pool):
                cid, sent = pool[used]
                used += 1
                if prompt_hash(question(kind, cid, sent)) not in avoid:
                    plan.append((kind, question(kind, cid, sent), cid, sent))
                    break
        reserved = {sent for kind, _, _, sent in plan if kind != "numeric"}
        # pass 2: build the items; distractors come ONLY from sentences that are not the key of any item in this set
        for kind, prompt, cid, sent in plan:
            if kind == "numeric":
                src = [c.chunk_id for c in req.chunks if "usable" in c.text.lower()][:1]
                items.append(PracticeItemDraft(kind="numeric", prompt=prompt, answer_key=sent, numeric_tolerance=0.0,
                                               difficulty=req.difficulty, source_chunk_ids=src))
            elif kind == "mcq":
                free = [(c, s2) for c, s2 in pool if s2 not in reserved]
                distract = [s2 for c, s2 in free if c != cid][:3] or [s2 for _, s2 in free][:3]
                if len(distract) < 2:
                    continue
                opts = sorted([sent, *distract], key=lambda o: _h(o, req.topic_id))
                items.append(PracticeItemDraft(kind="mcq", prompt=prompt, options=opts, answer_key=sent, difficulty=req.difficulty,
                                               source_chunk_ids=[cid], distractor_tags={d: "mixes_up_related_statement" for d in distract}))
            else:
                key_terms = [t for t in dict.fromkeys(_tokens(sent)) if len(t) > 3][:5]
                items.append(PracticeItemDraft(kind="short_text", prompt=prompt, answer_key=sent,
                                               rubric="Mentions: " + ", ".join(key_terms), difficulty=req.difficulty,
                                               source_chunk_ids=[cid]))
        if not items:
            raise ValueError("the supplied passages do not contain enough material for practice questions")
        return PracticeSet(items=items)

    # ------------------------------------------------------------------ evaluate (short text only)
    def evaluate_answer(self, req: EvaluateRequest) -> EvaluationOut:
        terms = [t.strip() for t in (req.rubric or "").replace("Mentions:", "").split(",") if t.strip()]
        ans = set(_tokens(req.student_answer))
        hit = [t for t in terms if _stem(t.lower()) in ans or t.lower() in req.student_answer.lower()]
        cov = len(hit) / len(terms) if terms else 0.0
        ok = cov >= 0.6
        unsure = 0.3 if (cov >= 0.8 or cov <= 0.2) else 0.6          # a keyword matcher is unsure in the middle
        return EvaluationOut(
            correct=ok, partial_credit=round(cov, 2), uncertainty=unsure,
            feedback=("Your answer covers the key points." if ok else
                      "Your answer is missing key points: " + ", ".join(t for t in terms if t not in hit) + "."),
            error_tags=[] if ok else ["missing_key_terms"], evidence="matched: " + (", ".join(hit) or "nothing"))
